// src/components/audio/AudioSlider.tsx

interface AudioSliderProps {
  value: number;
  onChange: (value: number) => void;
  label: string;
  min?: number;
  max?: number;
  step?: number;
}

export default function AudioSlider({
  value,
  onChange,
  label,
  min = 0,
  max = 100,
  step = 1
}: AudioSliderProps) {
  return (
    <div className="flex flex-col gap-2">
      <label className="text-xs text-slate-400">{label}</label>
      <div className="relative w-full h-1 rounded bg-slate-700">
        <div
          className="absolute h-1 rounded bg-cyan-400"
          style={{ width: `${((value - min) / (max - min)) * 100}%` }}
        />
        <input
          type="range"
          min={min}
          max={max}
          step={step}
          value={value}
          onChange={(e) => onChange(Number(e.target.value))}
          className="absolute inset-0 w-full opacity-0 cursor-pointer"
        />
      </div>
    </div>
  );
}

// src/components/audio/AudioSlider.svelte
<script lang="ts">
  interface Props {
    value: number;
    label: string;
    min?: number;
    max?: number;
    step?: number;
    onChange?: (value: number) => void;
  }

  let {
    value = $bindable(0),
    label,
    min = 0,
    max = 100,
    step = 1,
    onChange
  }: Props = $props();

  let percent = $derived(max > min ? Math.max(0, Math.min(100, ((value - min) / (max - min)) * 100)) : 0);

  function handleInput(e: Event & { currentTarget: HTMLInputElement }) {
    const val = Number(e.currentTarget.value);
    value = val;
    onChange?.(val);
  }
</script>

<div class="flex flex-col gap-2">
  <label class="text-xs text-slate-400">{label}</label>
  <div class="relative w-full h-1 rounded bg-slate-700">
    <div
      class="absolute h-1 rounded bg-cyan-400"
      style:width="{percent}%"
    ></div>
    <input
      type="range"
      {min}
      {max}
      {step}
      {value}
      oninput={handleInput}
      class="absolute inset-0 w-full opacity-0 cursor-pointer"
    />
  </div>
</div>
