// src/components/widgets/WidgetRenderer.svelte
<script lang="ts">
  import type { WidgetType } from "../../types/layout.ts";
  import FolderExplorerWidget from "./FolderExplorerWidget.svelte";
  import VirtualTrackList from "./VirtualTrackList.svelte";
  import CoverWidget from "./CoverWidget.svelte";
  import InspectorWidget from "./InspectorWidget.svelte";
  import EqBarsWidget from "./EqBarsWidget.svelte";
  import DacTelemetryWidget from "./DacTelemetryWidget.svelte";
  import StandaloneSpectrumWidget from "./StandaloneSpectrumWidget.svelte";
  import QueueWidget from "./QueueWidget.svelte";
  import CavaVisualizer from "./CavaVisualizer.svelte";
  import BpmWidget from "./BpmWidget.svelte";
  import Id3TagWidget from "./Id3TagWidget.svelte";
  import RadioWidget from "./RadioWidget.svelte";
  import BufferInspectorWidget from "./BufferInspectorWidget.svelte";
  import BufferInspectorCompactWidget from "./BufferInspectorCompactWidget.svelte";
  import EqCompactWidget from "./EqCompactWidget.svelte";
  import SignalStatsWidget from "./SignalStatsWidget.svelte";
  import ListeningStatsWidget from "./ListeningStatsWidget.svelte";
  import RadioTelemetryWidget from "./RadioTelemetryWidget.svelte";
  import AudioDiagnosticsWidget from "./AudioDiagnosticsWidget.svelte";
  import DacTelemetryCompactWidget from "./DacTelemetryCompactWidget.svelte";
  import SignalMonitorWidget from "./SignalMonitorWidget.svelte";
  import EqSpectrumWidget from "./EqSpectrumWidget.svelte";
  import LoudnessWidget from "./LoudnessWidget.svelte";
  import AudioTelemetryFullWidget from "./AudioTelemetryFullWidget.svelte";
  import StreamMusicModal from "./StreamMusicModal.svelte";

  interface Props {
    widget: WidgetType;
    nodeKey?: string;
    isEditing?: boolean;
  }

  let { widget, nodeKey = undefined, isEditing = false }: Props = $props();
</script>

{#if widget === "folder_explorer"}
  <FolderExplorerWidget />
{:else if widget === "tracklist"}
  <VirtualTrackList />
{:else if widget === "cover"}
  <CoverWidget />
{:else if widget === "inspector"}
  <InspectorWidget />
{:else if widget === "eq_bars"}
  <EqBarsWidget />
{:else if widget === "spectrum"}
  <StandaloneSpectrumWidget {nodeKey} {isEditing} />
{:else if widget === "cava_visualizer"}
  <CavaVisualizer {nodeKey} {isEditing} />
{:else if widget === "dac_telemetry"}
  <DacTelemetryWidget />
{:else if widget === "dac_telemetry_compact"}
  <DacTelemetryCompactWidget />
{:else if widget === "queue"}
  <QueueWidget />
{:else if widget === "bpm"}
  <BpmWidget />
{:else if widget === "id3_tags"}
  <Id3TagWidget />
{:else if widget === "radio"}
  <RadioWidget />
{:else if widget === "stream_music"}
  <StreamMusicModal embedded={true} />
{:else if widget === "buffer_inspector"}
  <BufferInspectorWidget />
{:else if widget === "buffer_inspector_compact"}
  <BufferInspectorCompactWidget />
{:else if widget === "buffer_inspector_basic"}
  <BufferInspectorWidget showStability={false} />
{:else if widget === "buffer_stability_compact"}
  <BufferInspectorWidget compactStability={true} />
{:else if widget === "eq_bars_compact"}
  <EqCompactWidget />
{:else if widget === "signal_stats"}
  <SignalStatsWidget />
{:else if widget === "listening_stats"}
  <ListeningStatsWidget />
{:else if widget === "radio_telemetry"}
  <RadioTelemetryWidget />
{:else if widget === "audio_diagnostics"}
  <AudioDiagnosticsWidget />
{:else if widget === "signal_monitor_compact"}
  <SignalMonitorWidget />
{:else if widget === "eq_spectrum"}
  <EqSpectrumWidget />
{:else if widget === "loudness_normalizer"}
  <LoudnessWidget />
{:else if widget === "audio_telemetry_full"}
  <AudioTelemetryFullWidget />
{:else}
  <div class="p-4 text-center text-audiophile-muted font-mono text-xs">
    Widget desconocido: {widget}
  </div>
{/if}

// src/components/widgets/WidgetRenderer.tsx
import React from "react";
import type { WidgetType } from "../../types/layout.ts";
import { FolderExplorerWidget } from "./FolderExplorerWidget.tsx";
import { VirtualTrackList } from "./VirtualTrackList.tsx";
import { CoverWidget } from "./CoverWidget.tsx";
import { InspectorWidget } from "./InspectorWidget.tsx";
import { EqBarsWidget } from "./EqBarsWidget.tsx";
import { DacTelemetryWidget } from "./DacTelemetryWidget.tsx";
import { StandaloneSpectrumWidget } from "./StandaloneSpectrumWidget.tsx";
import { QueueWidget } from "./QueueWidget.tsx";
import { CavaVisualizer } from "./CavaVisualizer.tsx";
import { BpmWidget } from "./BpmWidget.tsx";
import { Id3TagWidget } from "./Id3TagWidget.tsx";
import { RadioWidget } from "./RadioWidget.tsx";
import { BufferInspectorWidget } from "./BufferInspectorWidget.tsx";
import { BufferInspectorCompactWidget } from "./BufferInspectorCompactWidget.tsx";
import { EqCompactWidget } from "./EqCompactWidget.tsx";
import { SignalStatsWidget } from "./SignalStatsWidget.tsx";
import { ListeningStatsWidget } from "./ListeningStatsWidget.tsx";
import { RadioTelemetryWidget } from "./RadioTelemetryWidget.tsx";
import { AudioDiagnosticsWidget } from "./AudioDiagnosticsWidget.tsx";
import { DacTelemetryCompactWidget } from "./DacTelemetryCompactWidget.tsx";
import { SignalMonitorWidget } from "./SignalMonitorWidget.tsx";
import { EqSpectrumWidget } from "./EqSpectrumWidget.tsx";
import { LoudnessWidget } from "./LoudnessWidget.tsx";
import { AudioTelemetryFullWidget } from "./AudioTelemetryFullWidget.tsx";
import { StreamMusicModal } from "./StreamMusicModal.tsx";

interface WidgetRendererProps {
  widget: WidgetType;
  nodeKey?: string;
  isEditing?: boolean;
}

export const WidgetRenderer: React.FC<WidgetRendererProps> = ({ widget, nodeKey, isEditing }) => {
  switch (widget) {
    case "folder_explorer":
      return <FolderExplorerWidget />;
    case "tracklist":
      return <VirtualTrackList />;
    case "cover":
      return <CoverWidget />;
    case "inspector":
      return <InspectorWidget />;
    case "eq_bars":
      return <EqBarsWidget />;
    case "spectrum":
      return <StandaloneSpectrumWidget nodeKey={nodeKey} isEditing={isEditing} />;
    case "cava_visualizer":
      return <CavaVisualizer nodeKey={nodeKey} isEditing={isEditing} />;
    case "dac_telemetry":
      return <DacTelemetryWidget />;
    case "dac_telemetry_compact":
      return <DacTelemetryCompactWidget />;
    case "queue":
      return <QueueWidget />;
    case "bpm":
      return <BpmWidget />;
    case "id3_tags":
      return <Id3TagWidget />;
    case "radio":
      return <RadioWidget />;
    case "stream_music":
      return <StreamMusicModal embedded />;
    case "buffer_inspector":
      return <BufferInspectorWidget />;
    case "buffer_inspector_compact":
      return <BufferInspectorCompactWidget />;
    case "buffer_inspector_basic":
      return <BufferInspectorWidget showStability={false} />;
    case "buffer_stability_compact":
      return <BufferInspectorWidget compactStability />;
    case "eq_bars_compact":
      return <EqCompactWidget />;
    case "signal_stats":
      return <SignalStatsWidget />;
    case "listening_stats":
      return <ListeningStatsWidget />;
    case "radio_telemetry":
      return <RadioTelemetryWidget />;
    case "audio_diagnostics":
      return <AudioDiagnosticsWidget />;
    case "signal_monitor_compact":
      return <SignalMonitorWidget />;
    case "eq_spectrum":
      return <EqSpectrumWidget />;
    case "loudness_normalizer":
      return <LoudnessWidget />;
    case "audio_telemetry_full":
      return <AudioTelemetryFullWidget />;
    default:
      return (
        <div className="p-4 text-center text-audiophile-muted font-mono text-xs">
          Widget desconocido: {widget}
        </div>
      );
  }
};
